// 分子構造のデータ
const structures = [
    {
        id: '2buk',
        name: 'Satellite tobacco necrosis virus (2buk)',
        url: 'https://files.rcsb.org/download/2BUK.pdb',
        format: 'pdb',
        tag: ['T1', 'paper'],
        snapshot: 'https://raw.githubusercontent.com/matsunagalab/capsid_view/main/snapshots/T1/2buk.molj', 
        mvsj: 'https://raw.githubusercontent.com/Sakura-Book/molstar_test/main/mvsj_files/T_1/Unclassified/Albetovirus/2buk.mvsj'
    },
    {
        id: '4v4m',
        name: 'STNV coat protein (4v4m)',
        url: 'https://files.rcsb.org/download/4V4M.cif',
        format: 'mmcif',
        tag: ['T1', 'paper'],
        snapshot: 'https://raw.githubusercontent.com/matsunagalab/capsid_view/main/snapshots/T1/4v4m.molj', 
        mvsj: 'https://raw.githubusercontent.com/Sakura-Book/molstar_test/main/mvsj_files/T_1/Unclassified/Albetovirus/4v4m.mvsj'
    },
    {
        id: '6s44',
        name: 'Faba bean necrotic stunt virus (6s44)',
        url: 'https://files.rcsb.org/download/6S44.pdb',
        format: 'pdb',
        tag: ['T1', 'paper'],
        snapshot: 'https://raw.githubusercontent.com/matsunagalab/capsid_view/main/snapshots/T1/6s44.molj',  
        mvsj: 'https://raw.githubusercontent.com/Sakura-Book/molstar_test/main/mvsj_files/T_1/Nanoviridae/Nanovirus/6s44.mvsj'
    },
    {
        id: '7odw',
        name: 'Model of Haliangium ochraceum encapsulin (7odw)',
        url: 'https://files.rcsb.org/download/7ODW.pdb',
        format: 'pdb',
        tag: ['T1', 'paper'],
        snapshot: 'https://raw.githubusercontent.com/matsunagalab/capsid_view/main/snapshots/T1/7odw.molj', 
        mvsj: 'https://raw.githubusercontent.com/Sakura-Book/molstar_test/main/mvsj_files/T_1/Nanoparticles/Nanoparticles/7odw.mvsj'
    },
    {
        id: '3r0r',
        name: 'Porcine circovirus 2 (3r0r)',
        url: 'https://files.rcsb.org/download/3R0R.pdb',
        format: 'pdb', 
        tag: ['T1', 'paper'],
        snapshot: 'https://raw.githubusercontent.com/matsunagalab/capsid_view/main/snapshots/T1/3r0r.molj', 
        mvsj: 'https://raw.githubusercontent.com/Sakura-Book/molstar_test/main/mvsj_files/T_1/Circoviridae/Circovirus/3r0r.mvsj'
    },
    {
        id: '5zju',
        name: 'PCV2-like particle (5zju)',
        url: 'https://files.rcsb.org/download/5ZJU.pdb',
        format: 'pdb',
        tag: ['T1', 'paper'],
        snapshot: 'https://raw.githubusercontent.com/matsunagalab/capsid_view/main/snapshots/T1/5zju.molj', 
        mvsj: 'https://raw.githubusercontent.com/Sakura-Book/molstar_test/main/mvsj_files/T_1/Circoviridae/Circovirus/5zju.mvsj'
    },
    {
        id: '1stm',
        name: 'Satellite panicum mosaic virus (1stm)',
        url: 'https://files.rcsb.org/download/1STM.pdb',
        format: 'pdb',
        tag: ['T1', 'paper'], 
        snapshot: 'https://raw.githubusercontent.com/matsunagalab/capsid_view/main/snapshots/T1/1stm.molj', 
        mvsj: 'https://raw.githubusercontent.com/Sakura-Book/molstar_test/main/mvsj_files/T_1/Unclassified/Papanivirus/1stm.mvsj'
    },
    {
        id: '1vb4',
        name: 'Sesbania mosaic virus deletion mutant (1vb4)',
        url: 'https://files.rcsb.org/download/1VB4.pdb',
        format: 'pdb',
        tag: ['T1', 'paper'],
        snapshot: 'https://raw.githubusercontent.com/matsunagalab/capsid_view/main/snapshots/T1/1vb4.molj', 
        mvsj: 'https://raw.githubusercontent.com/Sakura-Book/molstar_test/main/mvsj_files/T_1/Solemoviridae/Sobemovirus/1vb4.mvsj'
    },
    {
        id: '1m1c',
        name: 'L-A virus (1m1c)',
        url: 'https://files.rcsb.org/download/1M1C.pdb',
        format: 'pdb',
        tag: ['T2'],
        tag: ['T1', 'paper'],
        snapshot: 'https://raw.githubusercontent.com/matsunagalab/capsid_view/main/snapshots/T2/1m1c.molj', 
    },
    {
        id: '1uf2',
        name: 'Inner layer of Rice dwarf virus (1uf2)',
        url: 'https://files.rcsb.org/download/1UF2.pdb',
        format: 'pdb',
        tag: ['T2', 'paper'],
        snapshot: 'https://raw.githubusercontent.com/matsunagalab/capsid_view/main/snapshots/T2/1uf2.molj', 
    },
    {
        id: '2btv',
        name: 'Inner layer of Bluetongue virus (2btv)',
        url: 'https://files.rcsb.org/download/2btv.pdb',
        format: 'pdb',
        tag: ['T2'],
        snapshot: 'https://raw.githubusercontent.com/matsunagalab/capsid_view/main/snapshots/T2/2btv.molj',  
    },
    {
        id: '4btq',
        name: 'Pseudomonas phage phi6 (4btq)',
        url: 'https://files.rcsb.org/download/4btq.pdb',
        format: 'pdb',
        tag: ['T2'],
        snapshot: 'https://raw.githubusercontent.com/matsunagalab/capsid_view/main/snapshots/T2/4btq.molj', 
    },
    {
        id: '6r7m',
        name: 'Tobacco mosaic virus (6r7m)',
        url: 'https://files.rcsb.org/download/6R7M.pdb',
        format: 'pdb',
        tag: ['others', 'paper'],
        snapshot: 'https://raw.githubusercontent.com/matsunagalab/capsid_view/main/snapshots/others/6r7m.molj', 
    },
    {
        id: '2m99',
        name: 'Chymotrypsin inhibitor (2m99)',
        url: 'https://files.rcsb.org/download/2M99.pdb',
        format: 'pdb',
        tag: ['others', 'paper'],
        snapshot: 'https://raw.githubusercontent.com/matsunagalab/capsid_view/main/snapshots/others/2m99.molj', 
    },
    {
        id: '4sbv',
        name: 'southern bean mosaic virus (4sbv)',
        url: 'https://files.rcsb.org/download/4SBV.pdb',
        format: 'pdb',
        tag: ['T3'],
        snapshot: 'https://raw.githubusercontent.com/matsunagalab/capsid_view/main/snapshots/T3/4sbv.molj', 
    },
    {
        id: '6voc',
        name: 'icosahedral symmetry reconstruction of brome mosaic virus (6voc)',
        url: 'https://files.rcsb.org/download/6VOC.pdb',
        format: 'pdb',
        tag: ['T3'],
        snapshot: 'https://raw.githubusercontent.com/matsunagalab/capsid_view/main/snapshots/T3/6voc.molj', 
    },
    {
        id: '5kip',
        name: 'phage Qbeta (5kip)',
        url: 'https://files.rcsb.org/download/5KIP.pdb',
        format: 'pdb',
        tag: ['T3'],
        snapshot: 'https://raw.githubusercontent.com/matsunagalab/capsid_view/main/snapshots/T3/5kip.molj', 
    },
    {
        id: '5lqp',
        name: 'bacteriophage AP205 virus-like particles (5lqp)',
        url: 'https://files.rcsb.org/download/5LQP.cif',
        format: 'mmcif',
        tag: ['T3'],
        snapshot: 'https://raw.githubusercontent.com/matsunagalab/capsid_view/main/snapshots/T3/5lqp.molj', 
    },
    {
        id: '6crj',
        name: 'Mouse norovirus model (6crj)',
        url: 'https://files.rcsb.org/download/6CRJ.pdb',
        format: 'pdb',
        tag: ['T3'],
        snapshot: 'https://raw.githubusercontent.com/matsunagalab/capsid_view/main/snapshots/T3/6crj.molj', 
    },
    {
        id: '7bu8',
        name: 'zika virus complexed inner layer (7bu8)',
        url: 'https://files.rcsb.org/download/7BU8.pdb',
        format: 'pdb',
        tag: ['T3'],
        snapshot: 'https://raw.githubusercontent.com/matsunagalab/capsid_view/main/snapshots/T3/7bu8.molj', 
    },
    {
        id: '6idl',
        name: 'Dengue virus serotype 3 inner layer (6idl)',
        url: 'https://files.rcsb.org/download/6IDL.pdb',
        format: 'pdb',
        tag: ['T3'],
        snapshot: 'https://raw.githubusercontent.com/matsunagalab/capsid_view/main/snapshots/T3/6idl.molj', 
    },
    {
        id: '3j35',
        name: 'Dengue virus at 37 C (3j35)',
        url: 'https://files.rcsb.org/download/3J35.pdb',
        format: 'pdb',
        tag: ['T3'],
        snapshot: 'https://raw.githubusercontent.com/matsunagalab/capsid_view/main/snapshots/T3/3j35.molj', 
    },
    {
        id: '4b03',
        name: 'immature Dengue virus serotype 1 inner layer (4b03)',
        url: 'https://files.rcsb.org/download/4B03.pdb',
        format: 'pdb',
        tag: ['T3'],
        snapshot: 'https://raw.githubusercontent.com/matsunagalab/capsid_view/main/snapshots/T3/4b03.molj', 
    },
    {
        id: '1frs',
        name: 'bacteriophage fr capsid (1frs)',
        url: 'https://files.rcsb.org/download/1FRS.pdb',
        format: 'pdb',
        tag: ['T3'],
        snapshot: 'https://raw.githubusercontent.com/matsunagalab/capsid_view/main/snapshots/T3/1frs.molj', 
    },
    {
        id: '2e0z',
        name: 'virus-like particle from Pyrococcus furiosus (2e0z)',
        url: 'https://files.rcsb.org/download/2E0z.pdb',
        format: 'pdb',
        tag: ['T3'],
        snapshot: 'https://raw.githubusercontent.com/matsunagalab/capsid_view/main/snapshots/T3/2e0z.molj', 
    },
    {
        id: '8c0o',
        name: 'African cichlid nackednavirus capsid (8c0o)',
        url: 'https://files.rcsb.org/download/8C0O.cif',
        format: 'mmcif',
        tag: ['T3'],
        snapshot: 'https://raw.githubusercontent.com/matsunagalab/capsid_view/main/snapshots/T3/8c0o.molj', 
    },
    {
        id: '6yfa',
        name: 'Virus-like particle of bacteriophage AVE015 (6yfa)',
        url: 'https://files.rcsb.org/download/6YFA.cif',
        format: 'mmcif',
        tag: ['T3'],
        snapshot: 'https://raw.githubusercontent.com/matsunagalab/capsid_view/main/snapshots/T3/6yfa.molj', 
    },
    {
        id: '6bvn',
        name: 'Hepatitis B virus T=3 capsid (6bvn)',
        url: 'https://files.rcsb.org/download/6BVN.pdb',
        format: 'pdb',
        tag: ['T3'],
        snapshot: 'https://raw.githubusercontent.com/matsunagalab/capsid_view/main/snapshots/T3/6bvn.molj', 
    },
];

export {structures};